// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/WatchMessageBody.proto

package com.netty.demo.server.model.proto;

public final class WatchMessageBodyProto {
  private WatchMessageBodyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.netty.demo.server.model.proto.Model)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *工厂 3G
     * </pre>
     *
     * <code>string factory = 1;</code>
     */
    java.lang.String getFactory();
    /**
     * <pre>
     *工厂 3G
     * </pre>
     *
     * <code>string factory = 1;</code>
     */
    com.google.protobuf.ByteString
        getFactoryBytes();

    /**
     * <pre>
     *设备id 3918173069
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     *设备id 3918173069
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *内容长度的长度   消息类型+消息主体 = 内容长度
     * </pre>
     *
     * <code>string length = 3;</code>
     */
    java.lang.String getLength();
    /**
     * <pre>
     *内容长度的长度   消息类型+消息主体 = 内容长度
     * </pre>
     *
     * <code>string length = 3;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     *消息主体
     * </pre>
     *
     * <code>string body = 5;</code>
     */
    java.lang.String getBody();
    /**
     * <pre>
     *消息主体
     * </pre>
     *
     * <code>string body = 5;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string timeStamp = 6;</code>
     */
    java.lang.String getTimeStamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string timeStamp = 6;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string sender = 7;</code>
     */
    java.lang.String getSender();
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string sender = 7;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string receiver = 8;</code>
     */
    java.lang.String getReceiver();
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string receiver = 8;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <pre>
     *用户组编号
     * </pre>
     *
     * <code>string groupId = 9;</code>
     */
    java.lang.String getGroupId();
    /**
     * <pre>
     *用户组编号
     * </pre>
     *
     * <code>string groupId = 9;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();
  }
  /**
   * Protobuf type {@code com.netty.demo.server.model.proto.Model}
   */
  public  static final class Model extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.netty.demo.server.model.proto.Model)
      ModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Model.newBuilder() to construct.
    private Model(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Model() {
      factory_ = "";
      deviceId_ = "";
      length_ = "";
      type_ = "";
      body_ = "";
      timeStamp_ = "";
      sender_ = "";
      receiver_ = "";
      groupId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Model(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              factory_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              length_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              timeStamp_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netty.demo.server.model.proto.WatchMessageBodyProto.internal_static_com_netty_demo_server_model_proto_Model_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netty.demo.server.model.proto.WatchMessageBodyProto.internal_static_com_netty_demo_server_model_proto_Model_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.class, com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.Builder.class);
    }

    public static final int FACTORY_FIELD_NUMBER = 1;
    private volatile java.lang.Object factory_;
    /**
     * <pre>
     *工厂 3G
     * </pre>
     *
     * <code>string factory = 1;</code>
     */
    public java.lang.String getFactory() {
      java.lang.Object ref = factory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        factory_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *工厂 3G
     * </pre>
     *
     * <code>string factory = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFactoryBytes() {
      java.lang.Object ref = factory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        factory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceId_;
    /**
     * <pre>
     *设备id 3918173069
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *设备id 3918173069
     * </pre>
     *
     * <code>string deviceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object length_;
    /**
     * <pre>
     *内容长度的长度   消息类型+消息主体 = 内容长度
     * </pre>
     *
     * <code>string length = 3;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        length_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容长度的长度   消息类型+消息主体 = 内容长度
     * </pre>
     *
     * <code>string length = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private volatile java.lang.Object body_;
    /**
     * <pre>
     *消息主体
     * </pre>
     *
     * <code>string body = 5;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息主体
     * </pre>
     *
     * <code>string body = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private volatile java.lang.Object timeStamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string timeStamp = 6;</code>
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>string timeStamp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 7;
    private volatile java.lang.Object sender_;
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string sender = 7;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>string sender = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 8;
    private volatile java.lang.Object receiver_;
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string receiver = 8;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收人
     * </pre>
     *
     * <code>string receiver = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 9;
    private volatile java.lang.Object groupId_;
    /**
     * <pre>
     *用户组编号
     * </pre>
     *
     * <code>string groupId = 9;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户组编号
     * </pre>
     *
     * <code>string groupId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFactoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, factory_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
      }
      if (!getLengthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, length_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, body_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, timeStamp_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, receiver_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, groupId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFactoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, factory_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
      }
      if (!getLengthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, length_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, body_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, timeStamp_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, receiver_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, groupId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netty.demo.server.model.proto.WatchMessageBodyProto.Model)) {
        return super.equals(obj);
      }
      com.netty.demo.server.model.proto.WatchMessageBodyProto.Model other = (com.netty.demo.server.model.proto.WatchMessageBodyProto.Model) obj;

      boolean result = true;
      result = result && getFactory()
          .equals(other.getFactory());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getLength()
          .equals(other.getLength());
      result = result && getType()
          .equals(other.getType());
      result = result && getBody()
          .equals(other.getBody());
      result = result && getTimeStamp()
          .equals(other.getTimeStamp());
      result = result && getSender()
          .equals(other.getSender());
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FACTORY_FIELD_NUMBER;
      hash = (53 * hash) + getFactory().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netty.demo.server.model.proto.WatchMessageBodyProto.Model prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.netty.demo.server.model.proto.Model}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.netty.demo.server.model.proto.Model)
        com.netty.demo.server.model.proto.WatchMessageBodyProto.ModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netty.demo.server.model.proto.WatchMessageBodyProto.internal_static_com_netty_demo_server_model_proto_Model_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netty.demo.server.model.proto.WatchMessageBodyProto.internal_static_com_netty_demo_server_model_proto_Model_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.class, com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.Builder.class);
      }

      // Construct using com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        factory_ = "";

        deviceId_ = "";

        length_ = "";

        type_ = "";

        body_ = "";

        timeStamp_ = "";

        sender_ = "";

        receiver_ = "";

        groupId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netty.demo.server.model.proto.WatchMessageBodyProto.internal_static_com_netty_demo_server_model_proto_Model_descriptor;
      }

      public com.netty.demo.server.model.proto.WatchMessageBodyProto.Model getDefaultInstanceForType() {
        return com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.getDefaultInstance();
      }

      public com.netty.demo.server.model.proto.WatchMessageBodyProto.Model build() {
        com.netty.demo.server.model.proto.WatchMessageBodyProto.Model result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netty.demo.server.model.proto.WatchMessageBodyProto.Model buildPartial() {
        com.netty.demo.server.model.proto.WatchMessageBodyProto.Model result = new com.netty.demo.server.model.proto.WatchMessageBodyProto.Model(this);
        result.factory_ = factory_;
        result.deviceId_ = deviceId_;
        result.length_ = length_;
        result.type_ = type_;
        result.body_ = body_;
        result.timeStamp_ = timeStamp_;
        result.sender_ = sender_;
        result.receiver_ = receiver_;
        result.groupId_ = groupId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netty.demo.server.model.proto.WatchMessageBodyProto.Model) {
          return mergeFrom((com.netty.demo.server.model.proto.WatchMessageBodyProto.Model)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netty.demo.server.model.proto.WatchMessageBodyProto.Model other) {
        if (other == com.netty.demo.server.model.proto.WatchMessageBodyProto.Model.getDefaultInstance()) return this;
        if (!other.getFactory().isEmpty()) {
          factory_ = other.factory_;
          onChanged();
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getLength().isEmpty()) {
          length_ = other.length_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netty.demo.server.model.proto.WatchMessageBodyProto.Model parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netty.demo.server.model.proto.WatchMessageBodyProto.Model) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object factory_ = "";
      /**
       * <pre>
       *工厂 3G
       * </pre>
       *
       * <code>string factory = 1;</code>
       */
      public java.lang.String getFactory() {
        java.lang.Object ref = factory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          factory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *工厂 3G
       * </pre>
       *
       * <code>string factory = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFactoryBytes() {
        java.lang.Object ref = factory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          factory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *工厂 3G
       * </pre>
       *
       * <code>string factory = 1;</code>
       */
      public Builder setFactory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        factory_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *工厂 3G
       * </pre>
       *
       * <code>string factory = 1;</code>
       */
      public Builder clearFactory() {
        
        factory_ = getDefaultInstance().getFactory();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *工厂 3G
       * </pre>
       *
       * <code>string factory = 1;</code>
       */
      public Builder setFactoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        factory_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <pre>
       *设备id 3918173069
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *设备id 3918173069
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *设备id 3918173069
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备id 3918173069
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *设备id 3918173069
       * </pre>
       *
       * <code>string deviceId = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <pre>
       *内容长度的长度   消息类型+消息主体 = 内容长度
       * </pre>
       *
       * <code>string length = 3;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容长度的长度   消息类型+消息主体 = 内容长度
       * </pre>
       *
       * <code>string length = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容长度的长度   消息类型+消息主体 = 内容长度
       * </pre>
       *
       * <code>string length = 3;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容长度的长度   消息类型+消息主体 = 内容长度
       * </pre>
       *
       * <code>string length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容长度的长度   消息类型+消息主体 = 内容长度
       * </pre>
       *
       * <code>string length = 3;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        length_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <pre>
       *消息主体
       * </pre>
       *
       * <code>string body = 5;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息主体
       * </pre>
       *
       * <code>string body = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息主体
       * </pre>
       *
       * <code>string body = 5;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息主体
       * </pre>
       *
       * <code>string body = 5;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息主体
       * </pre>
       *
       * <code>string body = 5;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string timeStamp = 6;</code>
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string timeStamp = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string timeStamp = 6;</code>
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string timeStamp = 6;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>string timeStamp = 6;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string sender = 7;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string sender = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string sender = 7;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string sender = 7;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>string sender = 7;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string receiver = 8;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string receiver = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string receiver = 8;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string receiver = 8;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人
       * </pre>
       *
       * <code>string receiver = 8;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <pre>
       *用户组编号
       * </pre>
       *
       * <code>string groupId = 9;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户组编号
       * </pre>
       *
       * <code>string groupId = 9;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户组编号
       * </pre>
       *
       * <code>string groupId = 9;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户组编号
       * </pre>
       *
       * <code>string groupId = 9;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户组编号
       * </pre>
       *
       * <code>string groupId = 9;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.netty.demo.server.model.proto.Model)
    }

    // @@protoc_insertion_point(class_scope:com.netty.demo.server.model.proto.Model)
    private static final com.netty.demo.server.model.proto.WatchMessageBodyProto.Model DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netty.demo.server.model.proto.WatchMessageBodyProto.Model();
    }

    public static com.netty.demo.server.model.proto.WatchMessageBodyProto.Model getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Model>
        PARSER = new com.google.protobuf.AbstractParser<Model>() {
      public Model parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Model(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Model> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Model> getParserForType() {
      return PARSER;
    }

    public com.netty.demo.server.model.proto.WatchMessageBodyProto.Model getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_demo_server_model_proto_Model_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_demo_server_model_proto_Model_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033java/WatchMessageBody.proto\022!com.netty" +
      ".demo.server.model.proto\"\234\001\n\005Model\022\017\n\007fa" +
      "ctory\030\001 \001(\t\022\020\n\010deviceId\030\002 \001(\t\022\016\n\006length\030" +
      "\003 \001(\t\022\014\n\004type\030\004 \001(\t\022\014\n\004body\030\005 \001(\t\022\021\n\ttim" +
      "eStamp\030\006 \001(\t\022\016\n\006sender\030\007 \001(\t\022\020\n\010receiver" +
      "\030\010 \001(\t\022\017\n\007groupId\030\t \001(\tB\027B\025WatchMessageB" +
      "odyProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_netty_demo_server_model_proto_Model_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netty_demo_server_model_proto_Model_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_demo_server_model_proto_Model_descriptor,
        new java.lang.String[] { "Factory", "DeviceId", "Length", "Type", "Body", "TimeStamp", "Sender", "Receiver", "GroupId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
